name: Build Wine Yolks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - wine/**

jobs:
  build:
    name: Build Wine ${{ matrix.folder }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: 8
            tag: wine-8

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: ./wine
          file: ./wine/${{ matrix.folder }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/Custom-Ptero-Stuff/custom-ptero-yolks:${{ matrix.tag }}
